---
title: "Paper: analysis"
format: html
---

## Background

## Data

```{r}
#| echo: FALSE

#loading necessary libraries and pulling in the rolling average function with source
library(dplyr)
library(tidyverse)
library(janitor)
library(lubridate)
library(here)
library(patchwork)
source(here("R", "rolling_avg.R"))

```

```{r}
#| warning: false
#read in Q1-Q3 and RMP datasets
prm <- read_csv(here::here("data", "RioMameyesPuenteRoto.csv"))

q1 <- read_csv(here::here("data", "QuebradaCuenca1-Bisley.csv"))

q2 <- read_csv(here::here("data", "QuebradaCuenca2-Bisley.csv"))

q3 <- read_csv(here::here("data", "QuebradaCuenca3-Bisley.csv"))

```

## Methods

```{r}
q1c_trial <- q1 |>
  select(Sample_Date, K) |>
  filter(Sample_Date <= "1994-12-27", Sample_Date >= "1988-01-05") |>
  mutate(K_mean = sapply(X = Sample_Date, 
                         FUN = roll_avg, 
                         sample_date = Sample_Date,
                         nutrient_conc = K, 
                         win_size_wks = 10))
```

```{r}
ggplot(q1c_trial, aes(x = Sample_Date, y = K_mean))+
  geom_line()

```

## Results
